import type { Config } from "tailwindcss";

// Ported 1:1 from the Stitch source's embedded tailwind.config (Ethereal
// Heritage system) so class names copied from the source HTML work verbatim.
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffe088",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        "primary-container": "#1b1b1b",
        "on-tertiary-container": "#a08000",
        tertiary: "#000000",
        "inverse-surface": "#2f3131",
        "secondary-container": "#dcdddd",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#848484",
        "marketplace-bronze": "#804A00",
        "on-surface": "#1a1c1c",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#454747",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container": "#eeeeee",
        "secondary-fixed-dim": "#c6c6c7",
        "on-primary-fixed": "#1b1b1b",
        "text-muted": "#757575",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        outline: "#7e7576",
        "tertiary-container": "#241a00",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        secondary: "#5d5f5f",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5f6161",
        primary: "#000000",
        "secondary-fixed": "#e2e2e2",
        surface: "#f9f9f9",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-dim": "#dadada",
        "on-primary-fixed-variant": "#474747",
        "tertiary-fixed-dim": "#e9c349",
        "inverse-primary": "#c6c6c6",
        "outline-variant": "#cfc4c5",
        "border-subtle": "#E5E5E5",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "on-tertiary-fixed-variant": "#574500",
        background: "#f9f9f9",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#5e5e5e",
        gold: "#a08000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
        "margin-tablet": "32px",
        "container-max": "1440px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1440px",
        container: "1440px",
      },
      fontFamily: {
        "label-md": ["var(--font-hanken)"],
        "display-lg": ["var(--font-playfair)"],
        "headline-md": ["var(--font-playfair)"],
        "headline-sm": ["var(--font-playfair)"],
        "label-sm": ["var(--font-hanken)"],
        "body-md": ["var(--font-hanken)"],
        "display-lg-mobile": ["var(--font-playfair)"],
        "body-lg": ["var(--font-hanken)"],
        display: ["var(--font-playfair)", "serif"],
        body: ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
